name: CI for Bookstore Backend

on:
  push:
    branches: [main, 'feature/**', 'test/**']
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      FLASK_ENV: development
      ENV: test
      PYTHONUNBUFFERED: 1  # ensures logs are not buffered

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Book Service
        run: |
          nohup flask run --port=5001 --app book_service > book_service.log 2>&1 &
          sleep 3

      - name: Start Auth Service
        run: |
          nohup flask run --port=5000 --app auth_service > auth_service.log 2>&1 &
          sleep 3

      - name: Run Unit Tests
        run: |
          pytest tests/**/unit/ \
            --cov=book_service --cov=auth_service --cov=common \
            --cov-report=term-missing --cov-report=html

      - name: Run Integration Tests
        run: |
          pytest tests/**/integration/ \
            --cov=book_service --cov=auth_service --cov=common \
            --cov-report=term-missing --cov-report=html

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: html-coverage-report
          path: htmlcov/
